version: '3.9'

services:
  php: &dev
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: development
    volumes:
      - .:/app
    expose:
      - "9000"
  composer:
    <<: *dev
    container_name: composer
    entrypoint: ["composer"]
    command: install -o --ignore-platform-reqs --no-scripts
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  npm:
    <<: *dev
    container_name: npm
    entrypoint: ["sh"]
    command: -c "npm install && npm run dev"
    